language: python
env:
  - TASK_VERSION=v2.4.0
  - TASK_VERSION=v2.4.1
  - TASK_VERSION=v2.4.2
  - TASK_VERSION=2.4.3
python:
  - "2.6"
  - "2.7"
before_install:
  # Setup virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Install testing tools
  - pip install pytest pytest-cov coveralls vimrunner
  - pip install git+git://github.com/robgolding63/tasklib@develop
  # Setup TaskWarrior
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake uuid-dev g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - git clone https://git.tasktools.org/scm/tm/task.git
  - cd task
  - git checkout $TASK_VERSION
  - git clean -dfx
  - cmake .
  - make
  - sudo make install
  - task --version
  # Setup Gvim
  - sudo apt-get install -qq vim-gnome
  - gvim --version
  # Setup vimwiki
  - mkdir -p ~/.vim/bundle
  - pushd ~/.vim/bundle
  - git clone https://github.com/vimwiki/vimwiki.git
  - popd
  - pushd ~/.vim/bundle/vimwiki/
  - git checkout dev
  - popd
  # Setup taskwiki
  - cp -r $TRAVIS_BUILD_DIR ~/.vim/bundle/taskwiki
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - py.test --cov . --cov-report term-missing
after_success:
  - coveralls
